version: '3'

services:
    www:
        build: src/php
        ports: 
            - "8080:80"
        volumes:
            - ./fin:/assets/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: registrybd
            MYSQL_USER: root
            MYSQL_PASSWORD: 8Pfvtxnjq+12
            MYSQL_ROOT_PASSWORD: 8Pfvtxnjq+12
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 8Pfvtxnjq+12
            MYSQL_ROOT_PASSWORD: 8Pfvtxnjq+12