CREATE DATABASE IF NOT EXISTS registrybd CHARACTER SET utf8 COLLATE utf8_general_ci;
USE registrybd

CREATE TABLE IF NOT EXISTS `users` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(255) DEFAULT NULL COMMENT 'Username',
	`email` VARCHAR(255) DEFAULT NULL COMMENT 'Email',
	`password` VARCHAR(255) DEFAULT NULL COMMENT 'Password',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE KEY `id` (`id`)
) COMMENT = 'Users';
